/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as UserRouteImport } from './routes/user'
import { Route as SurveyorRouteImport } from './routes/surveyor'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NgoRouteImport } from './routes/ngo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VolunteerIndexRouteImport } from './routes/volunteer.index'
import { Route as UserIndexRouteImport } from './routes/user.index'
import { Route as SurveyorIndexRouteImport } from './routes/surveyor.index'
import { Route as NgoIndexRouteImport } from './routes/ngo.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as VolunteerProfileRouteImport } from './routes/volunteer.profile'
import { Route as VolunteerNearbyRouteImport } from './routes/volunteer.nearby'
import { Route as VolunteerHistoryRouteImport } from './routes/volunteer.history'
import { Route as VolunteerAvailabilityRouteImport } from './routes/volunteer.availability'
import { Route as UserReportsRouteImport } from './routes/user.reports'
import { Route as UserProfileRouteImport } from './routes/user.profile'
import { Route as UserNotificationsRouteImport } from './routes/user.notifications'
import { Route as SurveyorRoutingRouteImport } from './routes/surveyor.routing'
import { Route as SurveyorReportsRouteImport } from './routes/surveyor.reports'
import { Route as SurveyorRegionRouteImport } from './routes/surveyor.region'
import { Route as SurveyorProfileRouteImport } from './routes/surveyor.profile'
import { Route as RegisterRoleRouteImport } from './routes/register.$role'
import { Route as NgoVolunteersRouteImport } from './routes/ngo.volunteers'
import { Route as NgoVerifyRouteImport } from './routes/ngo.verify'
import { Route as NgoSurveyorReportsRouteImport } from './routes/ngo.surveyor-reports'
import { Route as NgoProfileRouteImport } from './routes/ngo.profile'
import { Route as NgoAvailabilityRouteImport } from './routes/ngo.availability'
import { Route as NgoAnalyticsRouteImport } from './routes/ngo.analytics'
import { Route as NgoAcceptedRouteImport } from './routes/ngo.accepted'
import { Route as LoginRoleRouteImport } from './routes/login.$role'
import { Route as AdminRoutingRouteImport } from './routes/admin.routing'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminNgosRouteImport } from './routes/admin.ngos'
import { Route as AdminEscalationsRouteImport } from './routes/admin.escalations'
import { Route as AdminDuplicatesRouteImport } from './routes/admin.duplicates'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as UserReportsIdRouteImport } from './routes/user.reports.$id'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const UserRoute = UserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyorRoute = SurveyorRouteImport.update({
  id: '/surveyor',
  path: '/surveyor',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoRoute = NgoRouteImport.update({
  id: '/ngo',
  path: '/ngo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerIndexRoute = VolunteerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VolunteerRoute,
} as any)
const UserIndexRoute = UserIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UserRoute,
} as any)
const SurveyorIndexRoute = SurveyorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SurveyorRoute,
} as any)
const NgoIndexRoute = NgoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NgoRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const VolunteerProfileRoute = VolunteerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => VolunteerRoute,
} as any)
const VolunteerNearbyRoute = VolunteerNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => VolunteerRoute,
} as any)
const VolunteerHistoryRoute = VolunteerHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => VolunteerRoute,
} as any)
const VolunteerAvailabilityRoute = VolunteerAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => VolunteerRoute,
} as any)
const UserReportsRoute = UserReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => UserRoute,
} as any)
const UserProfileRoute = UserProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UserRoute,
} as any)
const UserNotificationsRoute = UserNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => UserRoute,
} as any)
const SurveyorRoutingRoute = SurveyorRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => SurveyorRoute,
} as any)
const SurveyorReportsRoute = SurveyorReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => SurveyorRoute,
} as any)
const SurveyorRegionRoute = SurveyorRegionRouteImport.update({
  id: '/region',
  path: '/region',
  getParentRoute: () => SurveyorRoute,
} as any)
const SurveyorProfileRoute = SurveyorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SurveyorRoute,
} as any)
const RegisterRoleRoute = RegisterRoleRouteImport.update({
  id: '/$role',
  path: '/$role',
  getParentRoute: () => RegisterRoute,
} as any)
const NgoVolunteersRoute = NgoVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => NgoRoute,
} as any)
const NgoVerifyRoute = NgoVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => NgoRoute,
} as any)
const NgoSurveyorReportsRoute = NgoSurveyorReportsRouteImport.update({
  id: '/surveyor-reports',
  path: '/surveyor-reports',
  getParentRoute: () => NgoRoute,
} as any)
const NgoProfileRoute = NgoProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => NgoRoute,
} as any)
const NgoAvailabilityRoute = NgoAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => NgoRoute,
} as any)
const NgoAnalyticsRoute = NgoAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => NgoRoute,
} as any)
const NgoAcceptedRoute = NgoAcceptedRouteImport.update({
  id: '/accepted',
  path: '/accepted',
  getParentRoute: () => NgoRoute,
} as any)
const LoginRoleRoute = LoginRoleRouteImport.update({
  id: '/$role',
  path: '/$role',
  getParentRoute: () => LoginRoute,
} as any)
const AdminRoutingRoute = AdminRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNgosRoute = AdminNgosRouteImport.update({
  id: '/ngos',
  path: '/ngos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEscalationsRoute = AdminEscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDuplicatesRoute = AdminDuplicatesRouteImport.update({
  id: '/duplicates',
  path: '/duplicates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const UserReportsIdRoute = UserReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => UserReportsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRouteWithChildren
  '/ngo': typeof NgoRouteWithChildren
  '/register': typeof RegisterRouteWithChildren
  '/surveyor': typeof SurveyorRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/volunteer': typeof VolunteerRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/duplicates': typeof AdminDuplicatesRoute
  '/admin/escalations': typeof AdminEscalationsRoute
  '/admin/ngos': typeof AdminNgosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/routing': typeof AdminRoutingRoute
  '/login/$role': typeof LoginRoleRoute
  '/ngo/accepted': typeof NgoAcceptedRoute
  '/ngo/analytics': typeof NgoAnalyticsRoute
  '/ngo/availability': typeof NgoAvailabilityRoute
  '/ngo/profile': typeof NgoProfileRoute
  '/ngo/surveyor-reports': typeof NgoSurveyorReportsRoute
  '/ngo/verify': typeof NgoVerifyRoute
  '/ngo/volunteers': typeof NgoVolunteersRoute
  '/register/$role': typeof RegisterRoleRoute
  '/surveyor/profile': typeof SurveyorProfileRoute
  '/surveyor/region': typeof SurveyorRegionRoute
  '/surveyor/reports': typeof SurveyorReportsRoute
  '/surveyor/routing': typeof SurveyorRoutingRoute
  '/user/notifications': typeof UserNotificationsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/reports': typeof UserReportsRouteWithChildren
  '/volunteer/availability': typeof VolunteerAvailabilityRoute
  '/volunteer/history': typeof VolunteerHistoryRoute
  '/volunteer/nearby': typeof VolunteerNearbyRoute
  '/volunteer/profile': typeof VolunteerProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/ngo/': typeof NgoIndexRoute
  '/surveyor/': typeof SurveyorIndexRoute
  '/user/': typeof UserIndexRoute
  '/volunteer/': typeof VolunteerIndexRoute
  '/user/reports/$id': typeof UserReportsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRouteWithChildren
  '/register': typeof RegisterRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/duplicates': typeof AdminDuplicatesRoute
  '/admin/escalations': typeof AdminEscalationsRoute
  '/admin/ngos': typeof AdminNgosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/routing': typeof AdminRoutingRoute
  '/login/$role': typeof LoginRoleRoute
  '/ngo/accepted': typeof NgoAcceptedRoute
  '/ngo/analytics': typeof NgoAnalyticsRoute
  '/ngo/availability': typeof NgoAvailabilityRoute
  '/ngo/profile': typeof NgoProfileRoute
  '/ngo/surveyor-reports': typeof NgoSurveyorReportsRoute
  '/ngo/verify': typeof NgoVerifyRoute
  '/ngo/volunteers': typeof NgoVolunteersRoute
  '/register/$role': typeof RegisterRoleRoute
  '/surveyor/profile': typeof SurveyorProfileRoute
  '/surveyor/region': typeof SurveyorRegionRoute
  '/surveyor/reports': typeof SurveyorReportsRoute
  '/surveyor/routing': typeof SurveyorRoutingRoute
  '/user/notifications': typeof UserNotificationsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/reports': typeof UserReportsRouteWithChildren
  '/volunteer/availability': typeof VolunteerAvailabilityRoute
  '/volunteer/history': typeof VolunteerHistoryRoute
  '/volunteer/nearby': typeof VolunteerNearbyRoute
  '/volunteer/profile': typeof VolunteerProfileRoute
  '/admin': typeof AdminIndexRoute
  '/ngo': typeof NgoIndexRoute
  '/surveyor': typeof SurveyorIndexRoute
  '/user': typeof UserIndexRoute
  '/volunteer': typeof VolunteerIndexRoute
  '/user/reports/$id': typeof UserReportsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRouteWithChildren
  '/ngo': typeof NgoRouteWithChildren
  '/register': typeof RegisterRouteWithChildren
  '/surveyor': typeof SurveyorRouteWithChildren
  '/user': typeof UserRouteWithChildren
  '/volunteer': typeof VolunteerRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/duplicates': typeof AdminDuplicatesRoute
  '/admin/escalations': typeof AdminEscalationsRoute
  '/admin/ngos': typeof AdminNgosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/routing': typeof AdminRoutingRoute
  '/login/$role': typeof LoginRoleRoute
  '/ngo/accepted': typeof NgoAcceptedRoute
  '/ngo/analytics': typeof NgoAnalyticsRoute
  '/ngo/availability': typeof NgoAvailabilityRoute
  '/ngo/profile': typeof NgoProfileRoute
  '/ngo/surveyor-reports': typeof NgoSurveyorReportsRoute
  '/ngo/verify': typeof NgoVerifyRoute
  '/ngo/volunteers': typeof NgoVolunteersRoute
  '/register/$role': typeof RegisterRoleRoute
  '/surveyor/profile': typeof SurveyorProfileRoute
  '/surveyor/region': typeof SurveyorRegionRoute
  '/surveyor/reports': typeof SurveyorReportsRoute
  '/surveyor/routing': typeof SurveyorRoutingRoute
  '/user/notifications': typeof UserNotificationsRoute
  '/user/profile': typeof UserProfileRoute
  '/user/reports': typeof UserReportsRouteWithChildren
  '/volunteer/availability': typeof VolunteerAvailabilityRoute
  '/volunteer/history': typeof VolunteerHistoryRoute
  '/volunteer/nearby': typeof VolunteerNearbyRoute
  '/volunteer/profile': typeof VolunteerProfileRoute
  '/admin/': typeof AdminIndexRoute
  '/ngo/': typeof NgoIndexRoute
  '/surveyor/': typeof SurveyorIndexRoute
  '/user/': typeof UserIndexRoute
  '/volunteer/': typeof VolunteerIndexRoute
  '/user/reports/$id': typeof UserReportsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/categories'
    | '/contact'
    | '/how-it-works'
    | '/login'
    | '/ngo'
    | '/register'
    | '/surveyor'
    | '/user'
    | '/volunteer'
    | '/admin/analytics'
    | '/admin/duplicates'
    | '/admin/escalations'
    | '/admin/ngos'
    | '/admin/reports'
    | '/admin/routing'
    | '/login/$role'
    | '/ngo/accepted'
    | '/ngo/analytics'
    | '/ngo/availability'
    | '/ngo/profile'
    | '/ngo/surveyor-reports'
    | '/ngo/verify'
    | '/ngo/volunteers'
    | '/register/$role'
    | '/surveyor/profile'
    | '/surveyor/region'
    | '/surveyor/reports'
    | '/surveyor/routing'
    | '/user/notifications'
    | '/user/profile'
    | '/user/reports'
    | '/volunteer/availability'
    | '/volunteer/history'
    | '/volunteer/nearby'
    | '/volunteer/profile'
    | '/admin/'
    | '/ngo/'
    | '/surveyor/'
    | '/user/'
    | '/volunteer/'
    | '/user/reports/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/categories'
    | '/contact'
    | '/how-it-works'
    | '/login'
    | '/register'
    | '/admin/analytics'
    | '/admin/duplicates'
    | '/admin/escalations'
    | '/admin/ngos'
    | '/admin/reports'
    | '/admin/routing'
    | '/login/$role'
    | '/ngo/accepted'
    | '/ngo/analytics'
    | '/ngo/availability'
    | '/ngo/profile'
    | '/ngo/surveyor-reports'
    | '/ngo/verify'
    | '/ngo/volunteers'
    | '/register/$role'
    | '/surveyor/profile'
    | '/surveyor/region'
    | '/surveyor/reports'
    | '/surveyor/routing'
    | '/user/notifications'
    | '/user/profile'
    | '/user/reports'
    | '/volunteer/availability'
    | '/volunteer/history'
    | '/volunteer/nearby'
    | '/volunteer/profile'
    | '/admin'
    | '/ngo'
    | '/surveyor'
    | '/user'
    | '/volunteer'
    | '/user/reports/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/categories'
    | '/contact'
    | '/how-it-works'
    | '/login'
    | '/ngo'
    | '/register'
    | '/surveyor'
    | '/user'
    | '/volunteer'
    | '/admin/analytics'
    | '/admin/duplicates'
    | '/admin/escalations'
    | '/admin/ngos'
    | '/admin/reports'
    | '/admin/routing'
    | '/login/$role'
    | '/ngo/accepted'
    | '/ngo/analytics'
    | '/ngo/availability'
    | '/ngo/profile'
    | '/ngo/surveyor-reports'
    | '/ngo/verify'
    | '/ngo/volunteers'
    | '/register/$role'
    | '/surveyor/profile'
    | '/surveyor/region'
    | '/surveyor/reports'
    | '/surveyor/routing'
    | '/user/notifications'
    | '/user/profile'
    | '/user/reports'
    | '/volunteer/availability'
    | '/volunteer/history'
    | '/volunteer/nearby'
    | '/volunteer/profile'
    | '/admin/'
    | '/ngo/'
    | '/surveyor/'
    | '/user/'
    | '/volunteer/'
    | '/user/reports/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRouteWithChildren
  NgoRoute: typeof NgoRouteWithChildren
  RegisterRoute: typeof RegisterRouteWithChildren
  SurveyorRoute: typeof SurveyorRouteWithChildren
  UserRoute: typeof UserRouteWithChildren
  VolunteerRoute: typeof VolunteerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user': {
      id: '/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof UserRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surveyor': {
      id: '/surveyor'
      path: '/surveyor'
      fullPath: '/surveyor'
      preLoaderRoute: typeof SurveyorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo': {
      id: '/ngo'
      path: '/ngo'
      fullPath: '/ngo'
      preLoaderRoute: typeof NgoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/': {
      id: '/volunteer/'
      path: '/'
      fullPath: '/volunteer/'
      preLoaderRoute: typeof VolunteerIndexRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/user/': {
      id: '/user/'
      path: '/'
      fullPath: '/user/'
      preLoaderRoute: typeof UserIndexRouteImport
      parentRoute: typeof UserRoute
    }
    '/surveyor/': {
      id: '/surveyor/'
      path: '/'
      fullPath: '/surveyor/'
      preLoaderRoute: typeof SurveyorIndexRouteImport
      parentRoute: typeof SurveyorRoute
    }
    '/ngo/': {
      id: '/ngo/'
      path: '/'
      fullPath: '/ngo/'
      preLoaderRoute: typeof NgoIndexRouteImport
      parentRoute: typeof NgoRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/volunteer/profile': {
      id: '/volunteer/profile'
      path: '/profile'
      fullPath: '/volunteer/profile'
      preLoaderRoute: typeof VolunteerProfileRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/volunteer/nearby': {
      id: '/volunteer/nearby'
      path: '/nearby'
      fullPath: '/volunteer/nearby'
      preLoaderRoute: typeof VolunteerNearbyRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/volunteer/history': {
      id: '/volunteer/history'
      path: '/history'
      fullPath: '/volunteer/history'
      preLoaderRoute: typeof VolunteerHistoryRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/volunteer/availability': {
      id: '/volunteer/availability'
      path: '/availability'
      fullPath: '/volunteer/availability'
      preLoaderRoute: typeof VolunteerAvailabilityRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/user/reports': {
      id: '/user/reports'
      path: '/reports'
      fullPath: '/user/reports'
      preLoaderRoute: typeof UserReportsRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/profile': {
      id: '/user/profile'
      path: '/profile'
      fullPath: '/user/profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof UserRoute
    }
    '/user/notifications': {
      id: '/user/notifications'
      path: '/notifications'
      fullPath: '/user/notifications'
      preLoaderRoute: typeof UserNotificationsRouteImport
      parentRoute: typeof UserRoute
    }
    '/surveyor/routing': {
      id: '/surveyor/routing'
      path: '/routing'
      fullPath: '/surveyor/routing'
      preLoaderRoute: typeof SurveyorRoutingRouteImport
      parentRoute: typeof SurveyorRoute
    }
    '/surveyor/reports': {
      id: '/surveyor/reports'
      path: '/reports'
      fullPath: '/surveyor/reports'
      preLoaderRoute: typeof SurveyorReportsRouteImport
      parentRoute: typeof SurveyorRoute
    }
    '/surveyor/region': {
      id: '/surveyor/region'
      path: '/region'
      fullPath: '/surveyor/region'
      preLoaderRoute: typeof SurveyorRegionRouteImport
      parentRoute: typeof SurveyorRoute
    }
    '/surveyor/profile': {
      id: '/surveyor/profile'
      path: '/profile'
      fullPath: '/surveyor/profile'
      preLoaderRoute: typeof SurveyorProfileRouteImport
      parentRoute: typeof SurveyorRoute
    }
    '/register/$role': {
      id: '/register/$role'
      path: '/$role'
      fullPath: '/register/$role'
      preLoaderRoute: typeof RegisterRoleRouteImport
      parentRoute: typeof RegisterRoute
    }
    '/ngo/volunteers': {
      id: '/ngo/volunteers'
      path: '/volunteers'
      fullPath: '/ngo/volunteers'
      preLoaderRoute: typeof NgoVolunteersRouteImport
      parentRoute: typeof NgoRoute
    }
    '/ngo/verify': {
      id: '/ngo/verify'
      path: '/verify'
      fullPath: '/ngo/verify'
      preLoaderRoute: typeof NgoVerifyRouteImport
      parentRoute: typeof NgoRoute
    }
    '/ngo/surveyor-reports': {
      id: '/ngo/surveyor-reports'
      path: '/surveyor-reports'
      fullPath: '/ngo/surveyor-reports'
      preLoaderRoute: typeof NgoSurveyorReportsRouteImport
      parentRoute: typeof NgoRoute
    }
    '/ngo/profile': {
      id: '/ngo/profile'
      path: '/profile'
      fullPath: '/ngo/profile'
      preLoaderRoute: typeof NgoProfileRouteImport
      parentRoute: typeof NgoRoute
    }
    '/ngo/availability': {
      id: '/ngo/availability'
      path: '/availability'
      fullPath: '/ngo/availability'
      preLoaderRoute: typeof NgoAvailabilityRouteImport
      parentRoute: typeof NgoRoute
    }
    '/ngo/analytics': {
      id: '/ngo/analytics'
      path: '/analytics'
      fullPath: '/ngo/analytics'
      preLoaderRoute: typeof NgoAnalyticsRouteImport
      parentRoute: typeof NgoRoute
    }
    '/ngo/accepted': {
      id: '/ngo/accepted'
      path: '/accepted'
      fullPath: '/ngo/accepted'
      preLoaderRoute: typeof NgoAcceptedRouteImport
      parentRoute: typeof NgoRoute
    }
    '/login/$role': {
      id: '/login/$role'
      path: '/$role'
      fullPath: '/login/$role'
      preLoaderRoute: typeof LoginRoleRouteImport
      parentRoute: typeof LoginRoute
    }
    '/admin/routing': {
      id: '/admin/routing'
      path: '/routing'
      fullPath: '/admin/routing'
      preLoaderRoute: typeof AdminRoutingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ngos': {
      id: '/admin/ngos'
      path: '/ngos'
      fullPath: '/admin/ngos'
      preLoaderRoute: typeof AdminNgosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/escalations': {
      id: '/admin/escalations'
      path: '/escalations'
      fullPath: '/admin/escalations'
      preLoaderRoute: typeof AdminEscalationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/duplicates': {
      id: '/admin/duplicates'
      path: '/duplicates'
      fullPath: '/admin/duplicates'
      preLoaderRoute: typeof AdminDuplicatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/user/reports/$id': {
      id: '/user/reports/$id'
      path: '/$id'
      fullPath: '/user/reports/$id'
      preLoaderRoute: typeof UserReportsIdRouteImport
      parentRoute: typeof UserReportsRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminDuplicatesRoute: typeof AdminDuplicatesRoute
  AdminEscalationsRoute: typeof AdminEscalationsRoute
  AdminNgosRoute: typeof AdminNgosRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRoutingRoute: typeof AdminRoutingRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminDuplicatesRoute: AdminDuplicatesRoute,
  AdminEscalationsRoute: AdminEscalationsRoute,
  AdminNgosRoute: AdminNgosRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRoutingRoute: AdminRoutingRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface LoginRouteChildren {
  LoginRoleRoute: typeof LoginRoleRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginRoleRoute: LoginRoleRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface NgoRouteChildren {
  NgoAcceptedRoute: typeof NgoAcceptedRoute
  NgoAnalyticsRoute: typeof NgoAnalyticsRoute
  NgoAvailabilityRoute: typeof NgoAvailabilityRoute
  NgoProfileRoute: typeof NgoProfileRoute
  NgoSurveyorReportsRoute: typeof NgoSurveyorReportsRoute
  NgoVerifyRoute: typeof NgoVerifyRoute
  NgoVolunteersRoute: typeof NgoVolunteersRoute
  NgoIndexRoute: typeof NgoIndexRoute
}

const NgoRouteChildren: NgoRouteChildren = {
  NgoAcceptedRoute: NgoAcceptedRoute,
  NgoAnalyticsRoute: NgoAnalyticsRoute,
  NgoAvailabilityRoute: NgoAvailabilityRoute,
  NgoProfileRoute: NgoProfileRoute,
  NgoSurveyorReportsRoute: NgoSurveyorReportsRoute,
  NgoVerifyRoute: NgoVerifyRoute,
  NgoVolunteersRoute: NgoVolunteersRoute,
  NgoIndexRoute: NgoIndexRoute,
}

const NgoRouteWithChildren = NgoRoute._addFileChildren(NgoRouteChildren)

interface RegisterRouteChildren {
  RegisterRoleRoute: typeof RegisterRoleRoute
}

const RegisterRouteChildren: RegisterRouteChildren = {
  RegisterRoleRoute: RegisterRoleRoute,
}

const RegisterRouteWithChildren = RegisterRoute._addFileChildren(
  RegisterRouteChildren,
)

interface SurveyorRouteChildren {
  SurveyorProfileRoute: typeof SurveyorProfileRoute
  SurveyorRegionRoute: typeof SurveyorRegionRoute
  SurveyorReportsRoute: typeof SurveyorReportsRoute
  SurveyorRoutingRoute: typeof SurveyorRoutingRoute
  SurveyorIndexRoute: typeof SurveyorIndexRoute
}

const SurveyorRouteChildren: SurveyorRouteChildren = {
  SurveyorProfileRoute: SurveyorProfileRoute,
  SurveyorRegionRoute: SurveyorRegionRoute,
  SurveyorReportsRoute: SurveyorReportsRoute,
  SurveyorRoutingRoute: SurveyorRoutingRoute,
  SurveyorIndexRoute: SurveyorIndexRoute,
}

const SurveyorRouteWithChildren = SurveyorRoute._addFileChildren(
  SurveyorRouteChildren,
)

interface UserReportsRouteChildren {
  UserReportsIdRoute: typeof UserReportsIdRoute
}

const UserReportsRouteChildren: UserReportsRouteChildren = {
  UserReportsIdRoute: UserReportsIdRoute,
}

const UserReportsRouteWithChildren = UserReportsRoute._addFileChildren(
  UserReportsRouteChildren,
)

interface UserRouteChildren {
  UserNotificationsRoute: typeof UserNotificationsRoute
  UserProfileRoute: typeof UserProfileRoute
  UserReportsRoute: typeof UserReportsRouteWithChildren
  UserIndexRoute: typeof UserIndexRoute
}

const UserRouteChildren: UserRouteChildren = {
  UserNotificationsRoute: UserNotificationsRoute,
  UserProfileRoute: UserProfileRoute,
  UserReportsRoute: UserReportsRouteWithChildren,
  UserIndexRoute: UserIndexRoute,
}

const UserRouteWithChildren = UserRoute._addFileChildren(UserRouteChildren)

interface VolunteerRouteChildren {
  VolunteerAvailabilityRoute: typeof VolunteerAvailabilityRoute
  VolunteerHistoryRoute: typeof VolunteerHistoryRoute
  VolunteerNearbyRoute: typeof VolunteerNearbyRoute
  VolunteerProfileRoute: typeof VolunteerProfileRoute
  VolunteerIndexRoute: typeof VolunteerIndexRoute
}

const VolunteerRouteChildren: VolunteerRouteChildren = {
  VolunteerAvailabilityRoute: VolunteerAvailabilityRoute,
  VolunteerHistoryRoute: VolunteerHistoryRoute,
  VolunteerNearbyRoute: VolunteerNearbyRoute,
  VolunteerProfileRoute: VolunteerProfileRoute,
  VolunteerIndexRoute: VolunteerIndexRoute,
}

const VolunteerRouteWithChildren = VolunteerRoute._addFileChildren(
  VolunteerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRouteWithChildren,
  NgoRoute: NgoRouteWithChildren,
  RegisterRoute: RegisterRouteWithChildren,
  SurveyorRoute: SurveyorRouteWithChildren,
  UserRoute: UserRouteWithChildren,
  VolunteerRoute: VolunteerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
